/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mrjnkgigcdqnmzwamgfe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yam5rZ2lnY2Rxbm16d2FtZ2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMjMyNTgsImV4cCI6MjA5MjU5OTI1OH0.iixT3Li-ruCr58PeOREMn5gvmsDafTIJph66O-Ab_tI"